name: Upload Repository to strongdog2 Folder

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # Create a temporary directory and move all files except the temp directory itself into it
      - name: Reorganize files
        run: |
          mkdir tempdir
          shopt -s extglob dotglob
          mv !(tempdir) tempdir
          mv tempdir strongdog2

      # Sync with S3
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
